// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMTPHr0h88b-bZZ6t__3cdU8QL9zxy68o',
    appId: '1:185025997591:web:df7a304ea165e7cc8d6552',
    messagingSenderId: '185025997591',
    projectId: 'happy-event-78a5c',
    authDomain: 'happy-event-78a5c.firebaseapp.com',
    storageBucket: 'happy-event-78a5c.appspot.com',
    measurementId: 'G-QL7RS70XCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByDlBdP7zV7xTrAzmUPvFYKl1J56jv1GM',
    appId: '1:185025997591:android:0a666442f134112f8d6552',
    messagingSenderId: '185025997591',
    projectId: 'happy-event-78a5c',
    storageBucket: 'happy-event-78a5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzjiFRIia4K2_2M6BWjYfdqi_8MgJdN4M',
    appId: '1:185025997591:ios:203e4ca2189272e98d6552',
    messagingSenderId: '185025997591',
    projectId: 'happy-event-78a5c',
    storageBucket: 'happy-event-78a5c.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzjiFRIia4K2_2M6BWjYfdqi_8MgJdN4M',
    appId: '1:185025997591:ios:18ae7131d94ae79c8d6552',
    messagingSenderId: '185025997591',
    projectId: 'happy-event-78a5c',
    storageBucket: 'happy-event-78a5c.appspot.com',
    iosBundleId: 'com.example.mobileApp.RunnerTests',
  );
}
